### PR TITLE
add svelte-vite-ssr template

### PR DESCRIPTION
**Pull request by jiangfengming**
https://github.com/jiangfengming/svelte-vite-ssr
A Svelte project template with a powerful router, SSR (Server-Side Rendering), CSR (Client-Side Rendering), HMR (Hot Module Replacement), `<link rel="preload">` directives, and other nice features.

<br>

By submitting this pull request, I promise I have read the [contribution guidelines](/../contributing.md) twice and ensured my submission follows it.

### CODE REVIEW

**Comment by benmccann** [comment]
Why would people choose this over SvelteKit which is also powered by Vite and has those features?

**Comment by jiangfengming** [comment]
> Why would people choose this over SvelteKit which is also powered by Vite and has those features?

This template is more like a demo project of the [svelte-pilot](https://github.com/jiangfengming/svelte-pilot) router. With a standalone router, everyone could make a SSR project with ease. The key difference to SvelteKit is this router uses config file based approach (like vue-router). It does not constrains the file structure and naming, and it has a more flexible layout system.

**Comment by benmccann** [comment]
Maybe a description like the following would help people in choosing:
A project template demonstrating usage of the svelte-pilot router with Vite. svelte-pilot uses a config file based approach (like vue-router)

**Comment by jiangfengming** [comment]
> Maybe a description like the following would help people in choosing:
> A project template demonstrating usage of the svelte-pilot router with Vite. svelte-pilot uses a config file based approach (like vue-router)

Yes, this sounds exactly match the purpose.

**Pull request merged**
