### PR TITLE
Add evanleck/vim-svelte to "Editor extensions"

### PR DESCRIPTION
**Pull request by evanleck**
https://github.com/evanleck/vim-svelte

evanleck/vim-svelte adds syntax highlighting and indentation for `.svelte` files in Vim/Neovim.

<br>

By submitting this pull request, I promise I have read the [contribution guidelines](/../contributing.md) twice and ensured my submission follows it.

### CODE REVIEW

**Comment by antony** [comment]
@evanleck how does your plugin compare to https://github.com/leafOfTree/vim-svelte-plugin ?

Competition is healthy, but is there a way to differentiate between the two plugins?

Happy to merge two, but it might be nice for users to see the advantages/disadvantages of each solution.

**Comment by evanleck** [comment]
@antony I've never used that plugin, but based on the description I'd say the biggest difference is that my plugin doesn't support any preprocessing like Pug, CoffeeScript, etc. I'd left that off of my implementation because loading a lot of syntax definitions can bog Vim down and because preprocessing requires plugins beyond Svelte itself to work. I'd be happy to talk about consolidating efforts at some point if there's interest in that.

**Comment by orta** [comment]
Sidenote: we're also open to a definitive svelte-vim plugin living in sveltejs/langauge-tools (with [the same caveats I offered to atom-svelte](https://github.com/sveltejs/language-tools/issues/70#issuecomment-625883300) ) where it can live on the same CI as the svelte-language-server.

**Comment by leafOfTree** [comment]
Hi, thanks for your time. I think here are some special features https://github.com/leafOfTree/vim-svelte-plugin supports
- Less/Sass/Scss, Pug, Coffee, TypeScript.
- A builtin `foldexpr` fold method.
- emmet-vim HTML/CSS/JavaScript filetype detection.

**Comment by benmccann** [comment]
I don't use vim, so am not in any position to say one plugin is better than the other, so I'd probably lean towards merging both these PRs.

I wonder if it might be good to add to the descriptions so that users don't have to click through to figure out which to use. E.g. something like " - lightweight syntax highlighting and indentation" for one and " - supports Less/Sass/Scss, Pug, Coffee, TypeScript" on the other.

**Comment by leafOfTree** [comment]
I feel like that it's ok for users to try and find the one that fits most. These plugins are still under developing and there is not always such a big difference between them.

**Comment by antony** [comment]
I agree - I'll merge both of these PRs, after we've updated them to have a brief list of features (As listed above, thanks @leafOfTree and @evanleck )

**Comment by evanleck** [comment]
@antony I forgot to mention it earlier but my plugin also has built in support for matchit.vim and ALE.

**Comment by evanleck** [comment]
FWIW we've landed support for preprocessor languages: https://github.com/evanleck/vim-svelte/pull/8

**Comment by antony** [comment]
Closed in https://github.com/sveltejs/integrations/commit/2aabf58a6394709cd09157f520df7c608737bf18

**Pull request closed without merging**
