### PR TITLE
Add sapper-typescript-graphql-tailwindcss-template to list

### PR DESCRIPTION
**Pull request by mscofield0**
**https://github.com/mscofield0/sapper-typescript-graphql-tailwindcss-template**
**A template that starts off Sapper with Typescript, GraphQL through TypegraphQL and Tailwind CSS.**

<br>

- [x] By submitting this pull request, I promise I have read the [contribution guidelines](/../contributing.md) twice and ensured my submission follows it.

### CODE REVIEW

**Comment by antony** [comment]
Duplicate PR?

**Comment by mscofield0** [comment]
This is with GraphQL, the other is without it.

**Comment by mscofield0** [comment]
Oh I see it still hasn't been merged. This is not a duplicate

**Comment by benmccann** [comment]
I'm thinking we might want to remove the whole Sapper section and replace it with a SvelteKit section

**Pull request closed without merging**
